### ISSUE TITLE
syntax error on macos

### ISSUE THREAD

**Issue by rejozenger** [mondmann/ofcvs2svg-gantt#1]
Hey there,

For your information, when running this on the latest MacOS, I'll get the following error:

```
rejo@ix3:~/Downloads$ ofcsv2svg.py OmniFocus.csv
  File "/usr/local/bin/ofcsv2svg.py", line 18
    def __init__(self, data: Dict):
                           ^
SyntaxError: invalid syntax
```

**Comment by mondmann** [comment]
Hm. Which python version do you use?

**Comment by rejozenger** [comment]
```
rejo@ix3:~$ python --version
Python 2.7.15
```

**Comment by mondmann** [comment]
Well, the code is not yet compatible with python 2.x. If you try

    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install python3
    python3 ofcsv2svg.py OmniFocus.csv

it should work.  Does it?
